import { Injectable, Logger } from '@nestjs/common';
import {
    Document, Packer, Paragraph, Table, TableRow, TableCell,
    TextRun, HeadingLevel, AlignmentType, WidthType, BorderStyle,
    ShadingType, convertInchesToTwip, Header, Footer, PageNumber,
} from 'docx';
import { PrescriptionDocumentData } from './document.types';

/**
 * DocumentGeneratorService
 *
 * Responsible for generating production-grade clinical DOCX documents
 * using the `docx` library. Produces a Buffer ready for Supabase Storage upload.
 */
@Injectable()
export class DocumentGeneratorService {
    private readonly logger = new Logger(DocumentGeneratorService.name);

    // --- CLINIC BRANDING CONSTANTS ---
    private readonly CLINIC_NAME = 'Janmasethu Fertility & Maternity Clinic';
    private readonly CLINIC_ADDRESS = '123 Care Avenue, Bangalore, Karnataka 560001';
    private readonly CLINIC_PHONE = '+91 80 1234 5678';
    private readonly BRAND_COLOR = '1B6CA8';   // Sky Blue (Clinical OS brand)
    private readonly HEADER_BG = 'EBF4FF';     // Light blue header background

    /**
     * MAIN ENTRY POINT
     * Generates a prescription document and returns it as a Buffer.
     */
    async generatePrescriptionDocument(data: PrescriptionDocumentData): Promise<Buffer> {
        this.logger.log(`Generating prescription document for patient ${data.patient.id}`);

        const doc = new Document({
            creator: data.doctor.full_name,
            title: `Prescription — ${data.patient.full_name}`,
            description: `Clinical prescription generated by Janmasethu DFO System`,
            styles: {
                default: {
                    document: {
                        run: { font: 'Calibri', size: 22 }
                    }
                }
            },
            sections: [
                {
                    headers: {
                        default: this.buildHeader(data),
                    },
                    footers: {
                        default: this.buildFooter(),
                    },
                    properties: {
                        page: {
                            margin: {
                                top: convertInchesToTwip(1),
                                right: convertInchesToTwip(1),
                                bottom: convertInchesToTwip(1),
                                left: convertInchesToTwip(1),
                            }
                        }
                    },
                    children: [
                        ...this.buildClinicHeader(data),
                        this.buildDivider(),
                        ...this.buildPatientBlock(data),
                        ...this.buildDoctorBlock(data),
                        this.buildDivider(),
                        this.buildSectionTitle('💊 Prescription Details'),
                        this.buildMedicationTable(data),
                        ...this.buildNotesBlock(data),
                        ...this.buildSignatureBlock(data),
                        ...this.buildDisclaimer(),
                    ],
                }
            ]
        });

        const buffer = await Packer.toBuffer(doc);
        this.logger.log(`Document generated: ${buffer.length} bytes`);
        return buffer;
    }

    // ============================================================
    // PRIVATE BUILDER METHODS
    // ============================================================

    private buildHeader(data: PrescriptionDocumentData): Header {
        return new Header({
            children: [
                new Paragraph({
                    children: [
                        new TextRun({
                            text: this.CLINIC_NAME,
                            bold: true,
                            color: this.BRAND_COLOR,
                            size: 18,
                        }),
                    ],
                    alignment: AlignmentType.RIGHT,
                })
            ]
        });
    }

    private buildFooter(): Footer {
        return new Footer({
            children: [
                new Paragraph({
                    children: [
                        new TextRun({
                            text: 'This is a computer-generated prescription. Page ',
                            size: 16,
                            color: '888888',
                        }),
                        new TextRun({
                            children: [PageNumber.CURRENT],
                            size: 16,
                            color: '888888',
                        }),
                        new TextRun({
                            text: ' of ',
                            size: 16,
                            color: '888888',
                        }),
                        new TextRun({
                            children: [PageNumber.TOTAL_PAGES],
                            size: 16,
                            color: '888888',
                        }),
                    ],
                    alignment: AlignmentType.CENTER,
                })
            ]
        });
    }

    private buildClinicHeader(data: PrescriptionDocumentData): Paragraph[] {
        return [
            new Paragraph({
                children: [
                    new TextRun({
                        text: this.CLINIC_NAME,
                        bold: true,
                        size: 36,
                        color: this.BRAND_COLOR,
                    })
                ],
                alignment: AlignmentType.CENTER,
                spacing: { after: 100 }
            }),
            new Paragraph({
                children: [
                    new TextRun({
                        text: this.CLINIC_ADDRESS,
                        size: 20,
                        color: '555555',
                    })
                ],
                alignment: AlignmentType.CENTER,
            }),
            new Paragraph({
                children: [
                    new TextRun({
                        text: `Tel: ${this.CLINIC_PHONE}`,
                        size: 18,
                        color: '555555',
                    })
                ],
                alignment: AlignmentType.CENTER,
                spacing: { after: 200 }
            }),
        ];
    }

    private buildDivider(): Paragraph {
        return new Paragraph({
            border: {
                bottom: {
                    color: this.BRAND_COLOR,
                    space: 1,
                    style: BorderStyle.SINGLE,
                    size: 6,
                }
            },
            spacing: { after: 200 }
        });
    }

    private buildSectionTitle(title: string): Paragraph {
        return new Paragraph({
            text: title,
            heading: HeadingLevel.HEADING_2,
            spacing: { before: 300, after: 150 },
            children: [
                new TextRun({
                    text: title,
                    bold: true,
                    size: 26,
                    color: this.BRAND_COLOR,
                })
            ]
        });
    }

    private buildPatientBlock(data: PrescriptionDocumentData): Paragraph[] {
        return [
            new Paragraph({
                children: [
                    new TextRun({ text: 'PATIENT DETAILS', bold: true, size: 22, color: this.BRAND_COLOR })
                ],
                spacing: { before: 200, after: 100 }
            }),
            new Paragraph({
                children: [
                    new TextRun({ text: 'Name: ', bold: true, size: 20 }),
                    new TextRun({ text: data.patient.full_name, size: 20 }),
                    new TextRun({ text: '     Patient ID: ', bold: true, size: 20 }),
                    new TextRun({ text: data.patient.id.substring(0, 8).toUpperCase(), size: 20 }),
                ],
                spacing: { after: 80 }
            }),
            new Paragraph({
                children: [
                    new TextRun({ text: 'Journey Stage: ', bold: true, size: 20 }),
                    new TextRun({ text: data.patient.journey_stage.replace(/_/g, ' ').toUpperCase(), size: 20 }),
                    new TextRun({ text: '     Contact: ', bold: true, size: 20 }),
                    new TextRun({ text: data.patient.phone_number, size: 20 }),
                ],
                spacing: { after: 200 }
            }),
        ];
    }

    private buildDoctorBlock(data: PrescriptionDocumentData): Paragraph[] {
        return [
            new Paragraph({
                children: [
                    new TextRun({ text: 'PRESCRIBING CLINICIAN', bold: true, size: 22, color: this.BRAND_COLOR })
                ],
                spacing: { before: 100, after: 100 }
            }),
            new Paragraph({
                children: [
                    new TextRun({ text: 'Doctor: ', bold: true, size: 20 }),
                    new TextRun({ text: data.doctor.full_name, size: 20 }),
                ],
                spacing: { after: 80 }
            }),
            new Paragraph({
                children: [
                    new TextRun({ text: 'Specialization: ', bold: true, size: 20 }),
                    new TextRun({ text: data.doctor.specialization.join(', '), size: 20 }),
                ],
                spacing: { after: 80 }
            }),
            new Paragraph({
                children: [
                    new TextRun({ text: 'Date: ', bold: true, size: 20 }),
                    new TextRun({ text: new Date().toLocaleDateString('en-IN', { year: 'numeric', month: 'long', day: 'numeric' }), size: 20 }),
                ],
                spacing: { after: 200 }
            }),
        ];
    }

    private buildMedicationTable(data: PrescriptionDocumentData): Table {
        const headerRow = new TableRow({
            tableHeader: true,
            children: [
                this.buildHeaderCell('Medication'),
                this.buildHeaderCell('Dosage'),
                this.buildHeaderCell('Frequency'),
                this.buildHeaderCell('Duration'),
                this.buildHeaderCell('Instructions'),
            ]
        });

        const medRow = new TableRow({
            children: [
                this.buildDataCell(data.prescription.medication_name || '—'),
                this.buildDataCell(data.prescription.dosage || '—'),
                this.buildDataCell(data.prescription.frequency || '—'),
                this.buildDataCell(`${data.prescription.duration_days} days`),
                this.buildDataCell(data.prescription.special_instructions || 'As directed'),
            ]
        });

        return new Table({
            rows: [headerRow, medRow],
            width: { size: 100, type: WidthType.PERCENTAGE },
        });
    }

    private buildHeaderCell(text: string): TableCell {
        return new TableCell({
            shading: { type: ShadingType.SOLID, color: this.BRAND_COLOR },
            children: [
                new Paragraph({
                    children: [
                        new TextRun({ text, bold: true, color: 'FFFFFF', size: 20 })
                    ],
                    alignment: AlignmentType.CENTER,
                })
            ]
        });
    }

    private buildDataCell(text: string): TableCell {
        return new TableCell({
            children: [
                new Paragraph({
                    children: [new TextRun({ text, size: 20 })],
                    alignment: AlignmentType.CENTER,
                })
            ]
        });
    }

    private buildNotesBlock(data: PrescriptionDocumentData): Paragraph[] {
        if (!data.prescription.special_instructions && !data.consultation.clinical_notes) {
            return [];
        }

        return [
            new Paragraph({
                children: [
                    new TextRun({ text: '📋 Clinical Notes', bold: true, size: 24, color: this.BRAND_COLOR })
                ],
                spacing: { before: 300, after: 150 }
            }),
            new Paragraph({
                children: [
                    new TextRun({
                        text: data.consultation.clinical_notes || 'No additional clinical notes.',
                        size: 20,
                        italics: true,
                        color: '444444',
                    })
                ],
                spacing: { after: 200 }
            }),
        ];
    }

    private buildSignatureBlock(data: PrescriptionDocumentData): Paragraph[] {
        return [
            new Paragraph({ spacing: { before: 400 } }),
            new Paragraph({
                children: [
                    new TextRun({ text: '_______________________________', color: '888888', size: 20 }),
                ],
                alignment: AlignmentType.RIGHT,
            }),
            new Paragraph({
                children: [
                    new TextRun({ text: data.doctor.full_name, bold: true, size: 20 }),
                ],
                alignment: AlignmentType.RIGHT,
            }),
            new Paragraph({
                children: [
                    new TextRun({
                        text: `${data.doctor.specialization.join(' | ')} — ${this.CLINIC_NAME}`,
                        size: 18,
                        color: '888888',
                    }),
                ],
                alignment: AlignmentType.RIGHT,
            }),
        ];
    }

    private buildDisclaimer(): Paragraph[] {
        return [
            new Paragraph({ spacing: { before: 400 } }),
            new Paragraph({
                children: [
                    new TextRun({
                        text: '⚠️ DISCLAIMER: This prescription is valid for 30 days from date of issue. It is computer-generated and is valid without a physical signature.',
                        size: 16,
                        color: 'AA0000',
                        italics: true,
                    })
                ],
                alignment: AlignmentType.CENTER,
            })
        ];
    }
}
